### ISSUE TITLE
Upgrade to Talos v1.10

### ISSUE THREAD

**Issue by adampetrovic** [adampetrovic/home-ops#1218]
- siderolabs/i915 - Intel graphics driver
  - siderolabs/intel-ucode - Intel microcode updates
  - siderolabs/thunderbolt - Thunderbolt device support
  - siderolabs/gasket-driver - Google TPU driver
  - siderolabs/nut-client - Network UPS Tools client

1.  Create Schematic File
```
  customization:
    extraKernelArgs:
      - net.ifnames=0
      - apparmor=0
      - init_on_alloc=0
      - init_on_free=0
      - mitigations=off
    systemExtensions:
      officialExtensions:
        - siderolabs/i915
        - siderolabs/intel-ucode
        - siderolabs/thunderbolt
        - siderolabs/gasket-driver
        - siderolabs/nut-client
```

2. Upload Schematic to Image Factory

`curl -X POST --data-binary @schematic.yaml https://factory.talos.dev/schematics`

 `Expected response: {"id":"your-schematic-id-here"}`

3. Generate Custom Installer Image 
  # Use the returned schematic ID
  SCHEMATIC_ID="your-schematic-id-here"

  # Your custom installer image will be:
  # factory.talos.dev/installer/${SCHEMATIC_ID}:v1.10.4
